import Head from 'next/head'
import Image from 'next/image'
import SocialMedia from '../components/SocialMedia/SocialMedia'
import Wrapper from '../components/Wrapper/Wrapper'

export default function AboutMe() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper container="initial">
                <section className="section-box-column modal-no-padding">

                    <div className="modal-wrapper">
                        <div className="modal">
                            <header>
                                <div className="photo-and-user-info">
                                    <div className="image">
                                        <Image src="/images/user.jpg" width={350} height={350} objectFit="cover" className="rounded-full" />
                                    </div>
                                    <div className="user-info">
                                        <div className="user-tag">
                                            <h1>Emre Güney</h1>
                                            <h3>Frontend Developer</h3>
                                        </div>
                                        <SocialMedia />
                                    </div>
                                </div>
                            </header>
                            <div className="aboutme-container">
                                <h3>Who Am I?</h3>
                                <p>A self-taught frontend developer who is open to learning and innovation, works hard and learns fast. Also interested backend technologies and Web 3.0 👌</p>
                                <h3>What I like?</h3>
                                <p>For now, I'm trying to understand and improve myself about React.JS, Node.JS, Next.JS and Web 3.0 I've also been interested in HTML and CSS for a long time.</p>
                                <p>I want to learn more and more every day.</p>
                            </div>
                            <div className="aboutme-container">
                                <h3 className="centeronmobile">Technologies</h3>
                                <div className="horizontal-box">
                                    <li><Image src="/images/html5.png" width={70} height={70} objectFit="contain" /><span>HTML</span></li>
                                    <li><Image src="/images/css3.png" width={70} height={70} objectFit="contain" /><span>CSS</span></li>
                                    <li><Image src="/images/javascript.png" width={70} height={70} objectFit="contain" /><span>Javascript</span></li>
                                    <li><Image src="/images/react.png" width={70} height={70} objectFit="contain" /><span>React JS</span></li>
                                    <li><Image src="/images/redux.png" width={70} height={70} objectFit="contain" /><span>Redux</span></li>
                                    <li><Image src="/images/next.png" width={70} height={70} objectFit="contain" /><span>Next JS</span></li>
                                    <li><Image src="/images/node.png" width={70} height={70} objectFit="contain" /><span>Node</span></li>
                                    <li><Image src="/images/express.png" width={70} height={70} objectFit="contain" /><span>Express</span></li>
                                    <li><Image src="/images/mongodb.png" width={70} height={70} objectFit="contain" /><span>MongoDB</span></li>
                                    <li><Image src="/images/jwt.png" width={70} height={70} objectFit="contain" /><span>JWT</span></li>
                                    <li><Image src="/images/php.png" width={70} height={70} objectFit="contain" /><span>PHP</span></li>
                                    <li><Image src="/images/mysql.png" width={70} height={70} objectFit="contain" /><span>MySQL</span></li>
                                    <li><Image src="/images/sass.png" width={70} height={70} objectFit="contain" /><span>SaSS</span></li>
                                    <li><Image src="/images/tailwind.png" width={70} height={70} objectFit="contain" /><span>TailwindCSS</span></li>
                                    <li><Image src="/images/bootstrap.png" width={70} height={70} objectFit="contain" /><span>Bootstrap</span></li>
                                    <li><Image src="/images/git.png" width={70} height={70} objectFit="contain" /><span>Git</span></li>
                                    <li><Image src="/images/npm.png" width={70} height={70} objectFit="contain" /><span>Npm</span></li>
                                    <li><Image src="/images/yarn.png" width={70} height={70} objectFit="contain" /><span>Yarn</span></li>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </Wrapper>

        </>
    )
}
