import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Icons from '../components/UI/Icons'
import Wrapper from '../components/Wrapper/Wrapper'

export default function Portfolio() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper container="initial">
                <section className="section-box-column">
                    <label>
                        <h2 className="withIcon"><span className="icon"></span>My Portfolio</h2>
                        <p>Check out some of my projects 😏</p>
                    </label>
                    <div className="portfolio-list">
                        <li>
                            <Image src="/images/instagram.jpg" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>Mernstack React.js Instagram Clone</h3>
                                    <p>A mernstack Instagram clone app built in React.JS and Node.js</p>
                                </header>
                                <div className="links">
                                    <Link href="https://mern-react-instagram-clone.netlify.app/"><a className="demo">Demo</a></Link>
                                    <Link href="https://github.com/eeguney/mern-instagram-clone"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>

                        <li>
                            <Image src="/images/blog.jpg" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>Mernstack Next.js Blogging App</h3>
                                    <p>A elegance and MERN Full-Stack, blogging app written in Next.JS and Node.JS</p>
                                </header>
                                <div className="links">
                                    <Link href="http://emreguney.xyz/"><a className="demo">Demo</a></Link>
                                    <Link href="https://github.com/eeguney/mern-next.js-emreguney-blog"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>

                        <li>
                            <Image src="/images/money.jpg" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>Mernstack React Budget Planner App</h3>
                                    <p>A powerful, elegance and MERN Full-Stack, budget planning app written in React.JS</p>
                                </header>
                                <div className="links">
                                    <Link href="https://mern-react-budget-planner-app.netlify.app/"><a className="demo">Demo</a></Link>
                                    <Link href="https://github.com/eeguney/mern-react-budget-planner-app"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>

                        <li>
                            <Image src="/images/notebook.jpg" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>Mernstack TaskerX Task and Note Manager</h3>
                                    <p>TaskerX is an app for organize your tasks, notes and todo's. Built in React.js - Node.js and TailwindCSS</p>
                                </header>
                                <div className="links">
                                    <Link href="https://github.com/eeguney/mern-taskerx-task-and-note-manager"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>

                        <li>
                            <Image src="/images/opensea.jpeg" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>NextJS Opensea UI Clone</h3>
                                </header>
                                <div className="links">
                                    <Link href="https://github.com/eeguney/opensea-clone"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>

                        <li>
                            <Image src="/images/portfolio.png" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>NextJS Portfolio Site</h3>
                                    <p>A simple portfolio page designed and written by me, made up with CSS animations and written on NextJS</p>
                                </header>
                                <div className="links">
                                    <Link href="https://github.com/eeguney/my-portfolio-site"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>

                        <li>
                            <Image src="/images/tamercapital.png" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>NextJS TailwindCSS Tamer Capital UI Task</h3>
                                    <p>A sample task of a firm for recruitment</p>

                                </header>
                                <div className="links">
                                    <Link href="https://tamer-capital-task.netlify.app/"><a className="demo">Demo</a></Link>
                                    <Link href="https://github.com/eeguney/tamer-capital-task-tailwind"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>

                        <li>
                            <Image src="/images/vanilla-password.png" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>Vanilla Javascript Password Generator</h3>
                                    <p>Good looking and responsive password generator built in vanilla (pure) javascript.</p>
                                </header>
                                <div className="links">
                                    <Link href="https://github.com/eeguney/vanilla-javascript-password-generator"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>

                        <li>
                            <Image src="/images/vanilla-stopwatch.png" width={200} height={200} objectFit="cover" className="rounded-full" />
                            <div className="list-info">
                                <header>
                                    <h3>Vanilla Javascript Stopwatch Timer</h3>
                                    <p>A simple and elegance stopwatch (timer) written in Vanilla JS</p>
                                </header>
                                <div className="links">
                                    <Link href="https://github.com/eeguney/vanilla-js-stopwatch-timer"><a className="github"><Icons.Github size={22} /> Github</a></Link>
                                </div>
                            </div>
                        </li>
                        
                    </div>
                </section>
            </Wrapper>

        </>
    )
}
